---
- name: Look for existing network devices
  ansible.builtin.set_fact:
    device_serials: "{{ query('wwt.meraki.fetch',
      'network_devices',
      network_name=network.name,
      org_name=network.organization,
      meraki_api_key=auth_key) }}"

- name: Remove Devices
  cisco.meraki.networks_devices_remove:
    meraki_api_key: "{{ auth_key }}"
    networkId: "{{ network_id }}"
    serial: "{{ device }}"
  loop: "{{ device_serials }}"
  loop_control:
    loop_var: device
  when: device_serials is defined

- name: Remove Meraki Network
  cisco.meraki.networks:
    meraki_api_key: "{{ auth_key }}"
    state: absent
    networkId: "{{ network_id }}"
